### PR TITLE
1.2.4

### PR DESCRIPTION
**Pull request by GaryRidgway**

### CODE REVIEW

**Comment by richardbporter** [comment]
I think it would best if the `echo`'s were replace with `drush_log`.

**Comment by richardbporter** [comment]
Also I got this error running it locally:
```
menu_block is already enabled.                                           [ok]
There were no extensions that could be enabled.                          [ok]
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062      [error]
Duplicate entry 'adminimal-menu_block-1' for key 'tmd' in
```

**Comment by GaryRidgway** [comment]
did you run it on a fresh site install?

**Comment by GaryRidgway** [comment]
I have changed all of the `echo` calls to be `drush_print`.

**Pull request merged**
