### PR TITLE
Decide localize functionality

### LINKED ISSUE #31: Decide localize functionality
There are 4 environment cases in the localize command: local, dev, test and prod. Each case is outlined starting on https://github.com/ITS-UofIowa/herky/blob/issue-31/herky.drush.inc#L655

### PR DESCRIPTION
**Pull request by richardbporter**
Resolves #31 

How to test locally:
- In an acquia application, checkout this branch (issue-31) in the drush/contrib/herky directory.
- Run `drush herky-localize` (or `hloc` for short) against a local site.
- Review changes.
- Review code at https://github.com/ITS-UofIowa/herky/blob/issue-31/herky.drush.inc#L655 and comment here about what should/should not happen in each environment.

### CODE REVIEW

**Comment by briand44** [comment]
I don't think we should be disabling migrate in production. I know it is something that Insight says but some sites may have continuous migrations and not just a one time migration. This could break functionality on some sites.
https://github.com/ITS-UofIowa/herky/blob/issue-31/herky.drush.inc#L748

**Comment by richardbporter** [comment]
Sounds good. That was listed in our docs - we should update that as well.

**Comment by genjohnson** [comment]
I haven't a chance to try running the the command yet, but I've read through the code and have a couple questions.

1. Since `migrate` had been removed from the production pm-disable list, we probably want to remove it from the test pm-disable list as well.
2. Does passing `yes` to the `drush pm-disable` commands (like here: https://github.com/ITS-UofIowa/herky/blob/issue-31/herky.drush.inc#L697) force the modules and their dependents to be disabled?

**Comment by richardbporter** [comment]
Correct - it doesn't look like there is an option for pm-disable to fail-on-dependents or something like that. I even tested removing the `yes` option and it actually doesn't stop it from disabling dependencies. If that is a deal-breaker, we'd have to refactor that to be more intelligent.

**Comment by joewhitsitt** [comment]
Posted this on the issue as well #31 
>These look fine to me as long as we clean up features/modules that have some of these as dependencies. Searching our organization, these appear to be the modules affected for views_ui, field_ui:

> Profile code shouldn't matter and I don't think any module that isn't enabled matters either. Right? (e.g. engineering_development)
> 
> [views_ui](https://github.com/search?utf8=%E2%9C%93&q=org%3AITS-UofIowa+%22dependencies%5B%5D+%3D+views_ui%22&type=Code)
> 
> [field_ui](https://github.com/search?utf8=%E2%9C%93&q=org%3AITS-UofIowa+%22dependencies%5B%5D+%3D+field_ui%22&type=Code)
> 
> Thanks for the opt-out option!

**Comment by genjohnson** [comment]
@richardbporter thanks for the clarification on what happens with disabling modules. I'm okay leaving all the modules in the list to be disabled assuming that we don't force the localize command to be run for all sites (because some have legit dependencies on things like field_ui)

@joewhitsitt thanks, i've opened an issue to remove views_ui and field_ui from the of dependencies in sitenow_standard_profile https://github.com/ITS-UofIowa/sitenow_standard_profile/issues/138

**Comment by richardbporter** [comment]
I don't plan on running `heryk-locallize` on @sites. It will run automatically after a sql-sync. However, that shouldn't be an issue as most people are syncing to dev/test. I did configure test (stage) to disable the same modules as production with the idea that stage should be as close to production as possible. That was also a recommendation by support.

**Pull request merged**
